blueprint:
  name: Presence-activated Light with Quick Pass Mode
  description: >
    Allume une lumière lorsqu'une présence est détectée, et l'éteint immédiatement après pour les passages rapides, sauf si la lumière était déjà allumée.
  domain: automation
  input:
    presence_entity:
      name: Capteur de Présence
      description: Appareil capteur de présence
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    light_target:
      name: Lumière
      description: Appareil lumière
      selector:
        target:
          entity:
            domain: light
    bright_percentage:
      name: Pourcentage de Luminosité
      description: Niveau de luminosité que la lumière atteindra lorsqu'elle sera allumée
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
    no_motion_wait:
      name: Temps d'attente
      description: Temps en secondes pour laisser la lumière allumée après la dernière détection de mouvement
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    off_transition:
      name: Temps de Transition
      description: Temps en secondes pour l'extinction progressive de la lumière
      default: 0
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds
    light_sensor:
      name: Capteur de Lumière
      description: Capteur de lumière pour mesurer la luminosité ambiante
      default: ''
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    light_threshold:
      name: Seuil de Lumière
      description: Seuil inférieur du capteur de lumière
      default: 200
      selector:
        number:
          min: 0
          max: 100000
    quick_pass_time:
      name: Temps de Passage Rapide
      description: Temps maximum en secondes pour considérer un passage comme rapide
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

variables:
  presence_entity: !input presence_entity
  light_sensor: !input light_sensor
  light_threshold: !input light_threshold | float(0)
  quick_pass_time: !input quick_pass_time | float(0)
  no_motion_wait: !input no_motion_wait | int(0)
  off_transition: !input off_transition
  bright_percentage: !input bright_percentage
  light_was_on: "{{ is_state_attr(light_entity_id, 'state', 'on') }}"
  light_entity_id: "{{ expand(!input light_target) | map(attribute='entity_id') | list | first }}"

trigger:
  - platform: state
    entity_id: !input presence_entity
    from: 'off'
    to: 'on'

condition:
  - condition: template
    value_template: >
      {% if light_sensor != '' %}
        {{ states(light_sensor) | float(0) < light_threshold }}
      {% else %}
        true
      {% endif %}

action:
  - alias: "Enregistrer l'heure de début de présence"
    variables:
      presence_start_time: "{{ now() }}"

  - alias: "Allumer la lumière si elle n'est pas déjà allumée"
    condition:
      - condition: state
        entity_id: "{{ light_entity_id }}"
        state: 'off'
    then:
      - service: light.turn_on
        target: !input light_target
        data:
          brightness_pct: "{{ bright_percentage }}"

  - alias: "Attendre jusqu'à ce qu'il n'y ait plus de mouvement"
    wait_for_trigger:
      - platform: state
        entity_id: !input presence_entity
        from: 'on'
        to: 'off'

  - alias: "Calculer la durée de présence"
    variables:
      presence_duration: "{{ (as_timestamp(now()) - as_timestamp(presence_start_time)) | float(0) }}"

  - alias: "Décider d'appliquer le mode passage rapide"
    choose:
      - conditions:
          - condition: template
            value_template: >
              {{ presence_duration < quick_pass_time and not light_was_on }}
        sequence:
          - alias: "Éteindre la lumière après un passage rapide"
            service: light.turn_off
            target: !input light_target
            data:
              transition: "{{ off_transition }}"
    default:
      - alias: "Attendre le temps défini ou jusqu'à ce que la présence soit détectée à nouveau"
        wait_for_trigger:
          - platform: state
            entity_id: !input presence_entity
            to: 'on'
        timeout: "{{ no_motion_wait }}"
        continue_on_timeout: true

      - alias: "Vérifier si la présence est détectée à nouveau"
        choose:
          - conditions:
              - condition: state
                entity_id: !input presence_entity
                state: 'on'
            sequence:
              - alias: "La présence est détectée à nouveau, ne pas éteindre la lumière"
                # Ne rien faire, l'automatisation redémarrera grâce à 'mode: restart'
        default:
          - alias: "Éteindre la lumière après le délai sans mouvement"
            service: light.turn_off
            target: !input light_target
            data:
              transition: "{{ off_transition }}"
